CREATE DATABASE IF NOT EXISTS greenfield;

USE greenfield;

CREATE TABLE state (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  state VARCHAR(255) NOT NULL
);

CREATE TABLE parks (
  id INT NOT NULL PRIMARY KEY,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  lat INT NOT NULL,
  lon INT NOT NULL,
  description VARCHAR(255),
  rating INT DEFAULT 0
);

CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username VARCHAR(255) NOT NULL
);